Update mark attendance command
AY2425S1-CS2103T-W08-2/tp pull request #128
Opened 2024-10-23 03:36 UTC by gladwintan

1. Mark attendance command now takes in a date and tutorial of student to mark
2. Update UI to display tutorials and current week's attendance

2024-10-23 05:08 UTC, amitha2210 requested changes

2024-10-24 03:09 UTC, amitha2210 approved these changes
LGTM

2024-10-24 03:26 UTC, BlazeChron approved these changes
LGTM

2024-10-24 03:26 UTC, BlazeChron commented on src/main/java/seedu/address/logic/commands/MarkAttendanceByStudentCommand.java
> +                        String.format(MESSAGE_INVALID_TUTORIAL_FOR_STUDENT, tutorial)));
Nice use of streams, will update my own code to match.

2024-10-24 03:26 UTC, BlazeChron commented on src/main/java/seedu/address/logic/parser/MarkAttendanceByStudentCommandParser.java
> +            throw new ParseException(String.format("%s tutorial is not available at the center", tutorial));
Maybe saying center is too specific?

2024-10-24 03:27 UTC, Slipperybara commented on src/main/java/seedu/address/logic/commands/MarkAttendanceByStudentCommand.java
> +                studentToMarkAttendance.getPayment(), studentToMarkAttendance.getParticipation(),
Seems like if we do it this way, there is no need to unenroll and enroll. since the participation object will be updated

2024-10-24 03:28 UTC, Slipperybara reviewed
LGTM

2024-10-24 03:28 UTC, merged

2024-10-24 07:20 UTC, gladwintan commented on src/main/java/seedu/address/logic/parser/MarkAttendanceByStudentCommandParser.java
> +            throw new ParseException(String.format("%s tutorial is not available at the center", tutorial));
Yea will change that out